# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'HYEX_Swift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'Alamofire','~> 5.0.0'            #网络请求
pod 'SnapKit','~> 5.0.0'        #自动布局
pod 'SwiftyJSON','~> 4.0.0'
pod 'Toast-Swift', '~> 5.0.1'       #toast提示
pod 'Kingfisher', '~> 4.0’
pod 'SwiftPullToRefresh'
pod 'JXBanner'
pod 'CLImagePickerTool'
pod 'DryAliyunOSS-iOS'

end
